{
 "title": "Air Quality Monitoring Station Copia OUTDATED",
 "description": "Collection of Sensor Outputs from the Air Quality Monitoring Station",
 "tags": [ "AQStation" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Temperatura e Umidità", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Umidità",
   "type": "gauge",
   "description": "Livello attuale di umidità in percentuale",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT11_Humidity",
     "query": "SELECT \"value\" FROM \"DHT11_Humidity\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "description": "La temperatura percepita al momento in gradi celsius",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT11_Feels_Like",
     "query": "SELECT \"value\" FROM \"DHT11_Feels_Like\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storico della temperatura (Gradi Celsius)",
   "type": "graph",
   "description": "L'andamento della temperatura in gradi Celsius nell'ultima ora",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Temperature (Celsius)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT11_Temperature_Celsius",
     "query": "SELECT \"value\" FROM \"DHT11_Temperature_Celsius\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura Attuale (Celsius)",
   "type": "gauge",
   "description": "La temperatura attuale in gradi Celsius",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "targets": [
    {
     "measurement": "DHT11_Temperature_Celsius",
     "query": "SELECT \"value\" FROM \"autogen\".\"DHT11_Temperature_Celsius\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatura Attuale (Fahrenheit)",
   "type": "gauge",
   "description": "La temperatura attuale in gradi Fahrenheit",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "measurement": "DHT11_Temperature_Fahrenheit",
     "query": "SELECT mean(\"value\") FROM \"DHT11_Temperature_Celsius\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storico della temperatura (Gradi Fahrenheit)",
   "type": "graph",
   "description": "L'andamento della temperatura in gradi Fahrenheit nell'ultima ora",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Temperature (Fahrenheit)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT11_Temperature_Celsius",
     "query": "SELECT \"value\" FROM \"DHT11_Temperature_Fahrenheit\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "timestamp" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cos'è questa sezione?",
   "type": "text",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "content": "\n# A cosa serve questa sezione?\n\nQuesta sezione presenta la temperatura (sia in gradi Celsius che in gradi Fahrenheit) e il livello di umidità (relativa) attuale, oltre al grafico che mostra lo storico di questi valori nell'ultima ora.\n\n# Temperatura\n\nLa temperatura indica lo stato termico di un corpo o di un sistema. Più nello specifico, la temperatura è direttamente legata al movimento e alla vibrazione degli atomi.\n\nNella scala Celsius (o centigrada) la temperatura di fusione del ghiaccio corrisponde a 0 gradi mentre il punto di ebollizione dell'acqua corrisponde a 100 gradi.\nL'unità di misura della scala Celsius è il **grado centigrado** (**°C**)\n\nNella scala Fahrenheit la temperatura di fusione del ghiaccio è di 32 gradi, mentre la temperatura di ebollizione dell'acqua è di 212 gradi.\nL'unità di misura di questa scala è il **grado Fahrenheit** (**°F**)\n\n# Umidità\n\nL'umidità è la quantità di acqua o di vapore acqueo contenuta in una massa d'aria, in un corpo o in un sistema. Questa pagina indica l'umidità relativa, che viene misurata in Percentuale (%).",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storico dell'umidità (In percentuale)",
   "type": "graph",
   "description": "Il livello in percentuale dell'umidità nell'ultima ora",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DHT11_Humidity",
     "query": "SELECT \"value\" FROM \"DHT11_Humidity\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CO2, Fumo, NH3, NOx, Alcol, Benzene",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 }
  },
  {
   "title": "Storico dei rilevamenti MQ135",
   "type": "graph",
   "description": "Livello medio di CO2, Fumo, NH3, NOx, Alcol e Benzene rilevati dal sensore MQ135",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MQ135",
     "query": "SELECT \"value\" FROM \"MQ135\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Il sensore MQ135",
   "type": "text",
   "description": "Spiegazione di cosa il sensore misura e perchè è importante misurarlo.",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 31 },
   "content": "\n# MQ135\n\nMQ135 è un sensore di gas con la capacità di misurare i livelli di CO2, Fumo, NH3, NOx, Alcol e Benzene e offre una media dei loro livelli.\n\nLa **CO2**, o biossido di carbonio, è anche conosciuta come anidride carbonica. A temperatura ambiente si presenta come un gas incolore di odore e sapore acidulo.\nUna elevata concentrazione di CO2 può avere come effetto lo sviluppo di sindromi respiratorie in quanto, per assicurare livelli sufficienti di ossigeno nel sangue, i polmoni sono soggetti ad un maggiore carico di lavoro in ambieni ad alta densità di CO2. Inoltre, un elevato livello di CO2 può avere effetti a livello gastrointestinale, inclusi crampi e episodi di dissenteria.\nI sintomi più frequenti sono un senso di peso sul petto, difficoltà a respirare o parlare e una ridotta lucidità mentale.\n\nIl **fumo** è una dispersione colloidale di particelle solide in un gas. Solitamente è generato durante la liberazione di prodotti gassosi durante una reazione chimica, come ad esempio la combustione.\nL'inalazione di fumo può causare gravi lesioni e anche la morte. Molti composti del fumo possono essere tossici o irritanti.\nUno dei composti più pericolosi è il monossido di carbonio, che porta all'avvelenamento.\n\nL'**NH3**, anche chiamata ammoniaca (triidruro di azoto) è un composto dell'azoto che si presenta come un gas incolore dal caratteristico odore pungente.\nL'ammoniaca è irritante per le vie respiratorie e può provare sintomi gravi fino alla morte. Risulta inoltre irritante anche per gli occhi e può causare ulcerazioni.\nL'alta tossicità dell'NH3 può aumentare l'affinità dell'emoglobina per l'ossigeno fino a renderla incapace di rilasciarlo ai tessuti.\n\n**NOx** è una sigla che raggruppa tuggi gli ossidi di azoto, come ad esempio il monossido di azoto (**NO**), il diossido di azoto (**NO2**), e le loro eventuali miscele.\nGli ossidi di azoto possono aggravare seriamente le condizioni dei malati di asma, dei bambini e di chi soffre di malattie respiratorie croniche o cardiache.\nElevate concentrazioni, seppur rare, possono provocare problemi a respirazione polmonare, irritazioni a mucose e agli occhi.\nGli effetti a lungo termine possono manifestarsi come alterazioni polmonari a livello tissutale e cellulare, oltre ad un aumento della suscettibilità alle infezioni polmonari batteriche e virali.\nLa presenza degli ossidi di azoto è manifestata da un odore pungente anche a concentrazioni minime.\n\nL'etanolo, comunemente chiamato **alcol**, è un composto organico con formula chimica CH3-CH2-OH.\nRisulta volatile, infiammabile, trasparente con odore pungente.\nPuò causare irritazioni degli occhi e della pelle. Nausea, vomito e intossicazione sono sintomi comuni.\n\nIl **Benzene** è un idrocarburo aromatico monociclico con notevoli proprietà solventi.\nL'inalazione di elevati tassi di benzene può portare al decesso, mentre in concentrazioni più basse può generare sonnolenza, vertigini, tachicardia, mal di testa, tremori, stato confusionale e perdita di coscienza.\nIl principale effetto di una esposizione cronica al benzene è il danneggiamento di tessuti ossei e diminuzione di cellule nel midollo osseo con leucemia o anemia aplastica come possibili conseguenze finali.\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rilevamento attuale MQ135",
   "type": "gauge",
   "description": "Livello attuale di CO2, Fumo, NH3, NOx, Alcol e Benzene rilevati dal sensore MQ135",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "MQ135",
     "query": "SELECT \"value\" FROM \"MQ135\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Particolato", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Cos'è questa sezione?",
   "type": "text",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 51 },
   "content": "\n# Il Particolato\n\nIl **particolato** (detto anche \"particellato\", *Particulate Matter*, **\"PM\"**), uno degli inquinanti più comuni in aree urbane, è l'insieme di sostanze solide o liquide presenti nell'aria, con la quale formano una miscela detta *aerosol atmosferico*. Attualmente è la sesta causa di morte prematura al mondo.\n\nL'origine del particolato può essere sia naturale che artificiale ma generalmente la concentrazione è maggiore dove si svolgono le attività umane più inquinanti.\n\nOltre agli impatti negativi sul clima e sulle precipitazioni, particolato è dannoso sia per la salute umana che per quella degli altri esseri viventi. L'**Organizzazione mondiale per la sanità**(**WHO**, *World Health Organization*) ha classificato il particolato come cancerogeno.\nDiversi studi sostengono che l'inquinamento atmosferico da particolato abbia avuto un ruolo nella diffusione e nella persistenza di virus in sospensione nell'atmosfera come nel 2002 con l'infezione di SARS (*Sindrome Respiratoria Acuta Grave*) in Cina e nel 2012 con il MERS (*Sindrome Respiratoria Mediorientale da Coronavirus*) in Arabia Saudita.\n\nData la capacità del particolato di penetrare nel cervello e nei polmoni dal sangue, causando quindi malattie cardiache, respiratorie e morte prematura, è stato definito la più pericolosa forma di inquinamento atmosferico.\n\nInoltre, nelle ipotesi sulle cause dell'estinzione di massa del Cretaceo-Paleocene, un considerevole aumento del particolato nell'atmosfera terrestre è spesso citato come una di queste cause.\n\nIl particolato viene indicato come **PM** con a seguito il diametro delle particelle, ad esempio PM2.5 indica la concentrazione di particolato con diamentro inferiore o uguale a 2.5µm.",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Valore Attuale PM2.5",
   "type": "gauge",
   "description": "L'ultimo rilevamento di particolato 2.5",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 61 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PMS_PM2.5",
     "query": "SELECT \"value\" FROM \"PMS_PM2.5\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storico Rilevamenti PM2.5",
   "type": "graph",
   "description": "Storico dei valori di PM2.5 nell'ultima ora.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PMS_PM2.5",
     "query": "SELECT \"value\" FROM \"PMS_PM2.5\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Valore Attuale PM10",
   "type": "gauge",
   "description": "L'ultimo rilevamento di particolato 10",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 69 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PMS_PM10",
     "query": "SELECT \"value\" FROM \"PMS_PM10\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storico Rilevamenti PM10",
   "type": "graph",
   "description": "Storico dei valori di PM10 nell'ultima ora.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PMS_PM10",
     "query": "SELECT \"value\" FROM \"PMS_PM10\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Composti Organici Volatili e eCO2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }
  },
  {
   "title": "Che cos'è questa sezione",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 78 },
   "content": "\n# I composti organici volatili e l'eCO2\n\nI **Composti organici volatili** possono causare diversi effetti che vanno dal disagio sensoriale fino a alterazioni molto gravi dello stato di salute. Nel caso di alte concentrazioni in ambienti interni possono avere effetti pesanti a carico di molti organi e apparati. Alcuni di essi, ad esempio il benzene, sono riconosciuti come cancerogeni per l’uomo.\n\nIl valore di **eCO2** è la stima del valore di CO2, che può dare una idea della concentrazione reale."
  },
  {
   "title": "Valore Attuale TVoC",
   "type": "gauge",
   "description": "Concentrazione dei composti organici volatili",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 83 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PMS_N2.5",
     "query": "SELECT \"value\" FROM \"etvoc\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storico Rilevamenti TVoC",
   "type": "graph",
   "description": "Storico dei valori di PM10 nell'ultima ora.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PMS_N10",
     "query": "SELECT \"value\" FROM \"etvoc\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Valore Attuale eCO2",
   "type": "gauge",
   "description": "Concentrazione dei composti organici volatili",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 91 },
   "targets": [
    {
     "measurement": "PMS_N1.0",
     "query": "SELECT \"value\" FROM \"eco2\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storico Rilevamenti eCO2",
   "type": "graph",
   "description": "Storico dei valori di eCO2 nell'ultima ora.",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "PMS_N10",
     "query": "SELECT \"value\" FROM \"eco2\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}